name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2.4.3

    - name: Run your build or tests
      run: |
        chk=$(( $GITHUB_RUN_NUMBER - 1 ))
        sed -i "s|test-repo-1:$chk|test-repo-1:$GITHUB_RUN_NUMBER|" script.sh

