name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run your build or tests
      run: |
        chk=$(( $GITHUB_RUN_NUMBER - 1 ))
        echo $chk
        sed -i "s/test-repo-1:$chk/test-repo-1:$GITHUB_RUN_NUMBER/g" script.sh
        cat script.sh

