name: First Workflow
env:
  token: ${{ secrets.G_HUB_ACCESS_TOKEN }}
on:
  push:
    branches:
      - main
      - dev*
  workflow_dispatch:

jobs:
  build:
    runs-on: stg-api-v3

    steps:
    - name: checkout
      uses: actions/checkout@v3

    # - name: ${{ github.event.head_commit.message }}
    #   run: |
    #     echo $USER
    #     echo (${{ github.event.repository.html_url }}/commit/${{ github.event.head_commit.id }})
    #     chk=$(( $GITHUB_RUN_NUMBER - 1 ))
    #     echo $chk
    #     sed -i "s/test-repo-1:$chk/test-repo-1:$GITHUB_RUN_NUMBER/g" script.sh
    #     cat script.sh
    #     git config --global user.email "noorulqumar0@gmail.com"
    #     git config --global user.name "noorulqumar"
    #     git config --global user.email "noorulqumar0@gmail.com"
    #     git config --global user.name "noorulqumar"
    #     git add .
    #    #git commit -m "Version ${GITHUB_RUN_NUMBER}"
    #    # git push
    #    # git push https://noorulqumar:${{ secrets.G_HUB_ACCESS_TOKEN }}@github.com/noorulqumar/Afaq-Bahi-Task-Github-Action.git

