name: First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: update script
      run: |
        export G_HUB_ACCESS_TOKEN=${{secrets.G_HUB_ACCESS_TOKEN}}
        chk=$(( $GITHUB_RUN_NUMBER - 1 ))
        echo $chk
        sed -i "s/test-repo-1:$chk/test-repo-1:$GITHUB_RUN_NUMBER/g" script.sh
        cat script.sh
        git config --global user.email "noorulqumar0@gmail.com"
        git config --global user.name "noorulqumar"
        git add .
        git commit -m "version ${GITHUB_RUN_NUMBER}"
        https://noorulqumar:$G_HUB_ACCESS_TOKEN@github.com/noorulqumar/Afaq-Bahi-Task-Github-Action.git

