name: workflow
env:
  ACOUNT_Owner: "noorulqumar80"
  DOCKER_HUB_REPO: ""
  TAG_OF_IMAGE: "1.0.0"
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  clone-the-code:
    runs-on: ubuntu-latest
    steps:
      - name: abc
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build --tag $ACOUNT_Owner/$DOCKER_HUB_REPO:$TAG_OF_IMAGE .

      - name: Show Docker images
        run: docker images

    


