name: workflow
env:
  ACOUNT_Owner: "noorulqumar80"
  DOCKER_HUB_REPO: "26"
  TAG_OF_IMAGE: "1.0.0"
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Setup-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4


      - name: Check if Docker is installed
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
          else
            echo "Docker is not installed."
            # sudo apt update -y
            # sudo apt  install docker.io -y
            # sudo usermod -aG docker $USER
            # newgrp docker 
            # sleep 10
            # sudo systemctl start docker
          fi

      - name: Set up Docker
        if: steps.check.outputs.stdout == 'Docker is not installed.'
        uses: docker/setup-buildx-action@v1

      - name: Check Docker version
        run: docker --version

      - name: Build docker image
        run: docker build --tag $ACOUNT_Owner/$DOCKER_HUB_REPO:$TAG_OF_IMAGE .

      - name: Show Docker images
        run: docker images


    


