name: workflow
env:
  ACOUNT_Owner: "noorulqumar80"
  DOCKER_HUB_REPO: "my-image"
  TAG_OF_IMAGE: "1.0.0"
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Checkout:
    runs-on: self-hosted
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
  Check-Setup-docker:
    runs-on: self-hosted
    needs: [Setup-docker]
    steps:
      - name: Check if Docker is installed
        run: |
          if command -v docker &>/dev/null; then
            echo "Docker is installed."
          else
            echo "Docker is not installed."
            # sudo apt update -y
            # sudo apt  install docker.io -y
            # sudo usermod -aG docker $USER
            # newgrp docker 
            # sleep 10
            # sudo systemctl start docker
          fi

      - name: Set up Docker
        if: steps.check.outputs.stdout == 'Docker is not installed.'
        uses: docker/setup-buildx-action@v1
  Build-docker-image:
    runs-on: self-hosted
    needs: [Check-Setup-docker]
    steps:
      - name: Build docker image
        run: docker build --tag $ACOUNT_Owner/$DOCKER_HUB_REPO:$TAG_OF_IMAGE .

      - name: Show Docker images
        run: docker images

      - name : print DOCKER token
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"

  Push_image_to_docker_Hub:
    runs-on: self-hosted
    needs: [Build-docker-image]
    steps:
      - name: login to docker hub
        run: 'echo dckr_pat_wBQJTGPISkV8rfqG_BbmRjDJANQ | docker login -u noorulqumar80 --password-stdin'  

      - name: push image
        run: docker push $ACOUNT_Owner/$DOCKER_HUB_REPO:$TAG_OF_IMAGE




    


